export const ROUTING_URLS={
  APP_LOGIN:'login',
  APP_REGISTRATION:'registration',
  APP_PLAY:'play',
  APP_PLAY_VIDEO:'play-video',
  APP_PLAY_AUDIO:'play-audio',
  APP_PLAYLISTS:'playlists',
  APP_UPLOAD:'upload',
  APP_UPLOAD_VIDEO:'upload-video',
  APP_UPLOAD_AUDIO:'upload-audio',
  APP_RECORD_VIDEO:'record-video',
  APP_RECORD_AUDIO:'record-audio',
  APP_CHECK_VIDEO:'check-video',
  APP_CHECK_AUDIO:'check-audio',
  APP_FAVORITE_CLIPS:'favorite-clips',
  APP_FAVORITE_ARTISTS:'favorite-artists',
  APP_ARTIST_PAGE:'artist-page',
  APP_PROFILE:'profile',
  APP_EDIT_PROFILE:'edit-profile',
  APP_EXTERNAL_LINKS:'external-links',
  APP_PROFILE_UPLOADS:'profile-uploads',
  APP_VOTES_VIEWS_INFO:'profile-votes-views-info',
  APP_SELECT_LANGUAGE:'select-language'

}
